github.com:
    users:
        A-LEXLUTOR:
            oauth_token: ghu_PjdU55DbbCjhBrNaEghPJVTXjhfkBq46bQE3
        metaketing-web:
            oauth_token: ghu_vlRVOR0ERXDB4RHjgsGcrV67ZiY9oM3H5Jvp
    user: metaketing-web
    oauth_token: ghu_vlRVOR0ERXDB4RHjgsGcrV67ZiY9oM3H5Jvp
